name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          branch: main
          workflow_conclusion: success
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: PHP-7.4-web.wasm
          path: build/PHP-7.4-web.wasm
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          branch: main
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: PHP-8.0.0-web.wasm
          path: build/PHP-8.0.0-web.wasm
      - name: Zip artifacts
        run: |
          cd build
          zip -r ../php-7.4-web.zip PHP-7.4-web.wasm
          zip -r ../php-8.0.0-web.zip PHP-8.0.0-web.wasm
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload PHP-7.4-web
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: php-7.4-web.zip
          asset_name: php-7.4-web.zip
          asset_content_type: application/zip
      - name: Upload PHP-8.0.0-web
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: php-8.0.0-web.zip
          asset_name: php-8.0.0-web.zip
          asset_content_type: application/zip
